sonar.projectName=El Poblano
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=apps/backend/src,apps/frontend/src
sonar.tests=apps/backend/tests,tests/selenium
sonar.test.inclusions=apps/backend/tests/**/*.js,tests/selenium/**/*.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,tests/results/**,apps/backend/generated/**,apps/frontend/src/assets/**
sonar.coverage.exclusions=apps/backend/src/server.js,apps/frontend/src/main.jsx
sonar.cpd.exclusions=apps/backend/prisma/migrations/**

sonar.javascript.lcov.reportPaths=tests/results/fase7/cobertura.lcov
