sonar.projectName=El Poblano
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=apps/backend/src,apps/frontend/src
sonar.tests=apps/backend/tests,apps/frontend/tests,tests/results/fase6/selenium/tests
sonar.test.inclusions=apps/backend/tests/**/*.js,apps/frontend/tests/**/*.{js,jsx},tests/results/fase6/selenium/tests/**/*.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,tests/results/fase5/**,tests/results/fase6/selenium/reports/**,tests/results/fase6/jmeter/results/**,tests/results/fase6/jmeter/reports/**,tests/results/fase7/**,tests/results/fase8/**,tests/results/trazabilidad/**,apps/backend/generated/**,apps/frontend/src/assets/**
sonar.coverage.exclusions=apps/backend/src/server.js,apps/frontend/src/main.jsx
sonar.cpd.exclusions=apps/backend/prisma/migrations/**

sonar.javascript.lcov.reportPaths=tests/results/fase7/sonarqube/results/cobertura.lcov
